"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowRight, Bell, CalendarDays, ChartNoAxesCombined, ChevronDown, ChevronRight, CircleHelp, Copy, Eye, Grid2X2, Layers3, Menu, MessageCircle, Percent, Search, Share2, ShoppingBag, SlidersHorizontal, Users, WalletCards, X } from "lucide-react";
import { creatorCard, demoUser, navItems, opportunities } from "@/lib/data";
import type { CreatorCardData, LinkedInImportedProfile, NavSection } from "@/lib/types";
import { BrandSymbol, CreatorCard } from "@/components/creator-card";
import { AccountMenu } from "@/components/account-menu";
import { PrimaryButton, SecondaryButton, StatusPill, Surface } from "@/components/ui";

const iconMap = { grid: Grid2X2, card: WalletCards, store: ShoppingBag, layers: Layers3, chart: ChartNoAxesCombined, users: Users, wallet: WalletCards, percent: Percent, message: MessageCircle } as const;

export function CreatorWorkspace() {
  const [section, setSection] = useState<NavSection>("home");
  const [mobileOpen, setMobileOpen] = useState(false);
  const [tour, setTour] = useState(false);
  const [demo, setDemo] = useState(false);
  const [account, setAccount] = useState<{ name: string; email: string; picture?: string } | null>(null);
  const [card, setCard] = useState<CreatorCardData>(creatorCard);

  useEffect(() => {
    const sync = () => setSection((window.location.hash.replace("#", "") as NavSection) || "home");
    sync();
    window.addEventListener("hashchange", sync);
    const params = new URLSearchParams(window.location.search);
    setTour(params.get("tour") === "1");
    const isDemo = params.get("demo") === "1";
    setDemo(isDemo);
    if (isDemo) {
      setAccount({ name: demoUser.profile.name, email: demoUser.email });
      window.localStorage.setItem("naano-demo-session", JSON.stringify(demoUser));
    }
    fetch("/api/auth/session").then((response) => response.json()).then((data: { user?: { name: string; email: string; picture?: string } | null }) => setAccount(data.user || null)).catch(() => undefined);
    fetch("/api/workspace?role=creator", { cache: "no-store" }).then((response) => { if (!response.ok) throw new Error("workspace unavailable"); return response.json(); }).then((data: { creator?: { profile: CreatorCardData } }) => { const profile = data.creator?.profile; if (profile) { setCard(profile); setAccount((current) => current || { name: profile.name, email: "Naano account", picture: profile.avatarUrl }); } }).catch(() => undefined);
    if (!isDemo) {
      fetch("/api/auth/linkedin/session", { cache: "no-store" })
        .then((response) => response.json() as Promise<{ profile: LinkedInImportedProfile | null }>)
        .then(({ profile }) => {
          if (!profile) return;
          setAccount((current) => current || { name: profile.name, email: profile.email || "LinkedIn profile", picture: profile.picture });
          setCard((current) => ({ ...current, name: profile.name, avatarUrl: profile.picture }));
        })
        .catch(() => undefined);
    }
    return () => window.removeEventListener("hashchange", sync);
  }, []);

  const navigate = (id: NavSection) => { window.location.hash = id; setMobileOpen(false); };

  return <div className="min-h-screen bg-[var(--canvas)] text-[var(--ink)]"><TopBar onMenu={() => setMobileOpen(true)} demo={demo} account={account} /><Sidebar active={section} onNavigate={navigate} mobileOpen={mobileOpen} onClose={() => setMobileOpen(false)} /><main className="min-h-screen pt-[52px] lg:pl-[210px]"><div className="mx-0 max-w-[1660px] px-5 py-8 sm:px-8 lg:px-[22px]">{section === "home" && <Overview card={card} onNavigate={navigate} accountName={account?.name} />}{section === "profile" && <ProfilePage card={card} />}{section === "opportunities" && <OpportunitiesPage />}{section === "collabs" && <CollaborationsPage />}{section === "analytics" && <AnalyticsPage />}{section === "community" && <CommunityPage card={card} />}{section === "earnings" && <EarningsPage />}{section === "referrals" && <ReferralsPage />}{section === "messages" && <MessagesPage />}</div></main><AssistantBar />{tour && <TourOverlay section={section} onClose={() => { window.history.replaceState({}, "", "/creator#home"); setTour(false); }} onNavigate={navigate} />}</div>;
}

function TopBar({ onMenu, demo, account }: { onMenu: () => void; demo: boolean; account: { name: string; email: string; picture?: string } | null }) {
  const [language, setLanguage] = useState<"EN" | "FR">("EN");
  return <header className="fixed inset-x-0 top-0 z-30 flex h-[52px] items-center justify-between border-b border-[var(--line)] bg-white/95 px-4 backdrop-blur lg:pl-[232px] lg:pr-6"><button className="rounded-lg p-2 lg:hidden" onClick={onMenu} aria-label="Open navigation"><Menu size={20} /></button><div className="flex items-center gap-2 lg:ml-auto">{demo && <span className="hidden rounded-full border border-[#cbd8ff] bg-[var(--blue-soft)] px-3 py-1.5 text-[10px] font-semibold text-[var(--blue)] sm:inline">Demo creator</span>}{account && <span className="hidden max-w-[180px] truncate text-xs font-semibold text-[var(--muted)] sm:inline" title={account.email}>{account.name}</span>}<button className="hidden items-center gap-2 rounded-lg border border-[var(--line)] px-3 py-2 text-xs sm:flex"><WalletCards size={13} /> €0</button><button onClick={() => setLanguage(language === "EN" ? "FR" : "EN")} className="rounded-lg border border-[var(--line)] px-2.5 py-2 text-xs font-semibold" aria-label="Change language">{language} <span className="ml-1 text-[var(--subtle)]">{language === "EN" ? "FR" : "EN"}</span></button><button className="rounded-lg border border-[var(--line)] p-2" aria-label="Notifications"><Bell size={15} /></button><AccountMenu name={account?.name} email={account?.email} picture={account?.picture} demo={demo} /></div></header>;
}

function Sidebar({ active, onNavigate, mobileOpen, onClose }: { active: NavSection; onNavigate: (id: NavSection) => void; mobileOpen: boolean; onClose: () => void }) {
  return <><div className={`fixed inset-0 z-40 bg-[#172033]/30 lg:hidden ${mobileOpen ? "block" : "hidden"}`} onClick={onClose} /><aside className={`fixed bottom-0 left-0 top-0 z-50 w-[210px] overflow-y-auto border-r border-[var(--line)] bg-white px-3 py-5 transition-transform lg:translate-x-0 ${mobileOpen ? "translate-x-0" : "-translate-x-full"}`}><div className="mb-10 flex items-center justify-between px-2"><span className="brand-mark text-lg"><BrandSymbol /> <span>naano</span></span><button onClick={onClose} className="lg:hidden" aria-label="Close navigation"><X size={18} /></button></div><nav className="space-y-1">{navItems.map(({ id, label, icon }) => { const Icon = iconMap[icon as keyof typeof iconMap]; return <button key={id} title={label} onClick={() => onNavigate(id)} aria-label={label} aria-current={active === id ? "page" : undefined} className={`flex min-h-11 w-full items-center gap-3 rounded-xl px-2.5 py-2.5 text-left text-xs font-semibold transition ${active === id ? "bg-[var(--blue-soft)] text-[var(--blue)]" : "text-[#506079] hover:bg-[#f7f9fc]"}`}><Icon size={16} strokeWidth={1.7} /> <span>{label}</span></button>; })}</nav></aside></>;
}

function PageIntro({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description: string; action?: React.ReactNode }) { return <div className="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div>{eyebrow && <p className="mb-2 text-[10px] font-semibold uppercase tracking-[.14em] text-[var(--muted)]">{eyebrow}</p>}<h1 className="text-[30px] font-bold tracking-[-.055em] sm:text-[34px]">{title}</h1><p className="mt-1 text-sm text-[var(--muted)]">{description}</p></div>{action}</div>; }

function Overview({ card, onNavigate, accountName }: { card: CreatorCardData; onNavigate: (id: NavSection) => void; accountName?: string }) {
  return <><PageIntro eyebrow="Creator workspace" title={`Good to see you, ${accountName || "Devesh"}`} description="Your creator activity, at a glance." /><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Public post reach" value="—" detail="Import in progress" /><StatCard label="Public posts" value="0" detail="Original LinkedIn posts found" /><StatCard label="Public engagements" value="0" detail="Reactions, comments and reposts" /><StatCard label="LinkedIn followers" value="1K" detail="Imported from the public profile" /></div><div className="mt-4 grid gap-4 xl:grid-cols-[488px_1fr]"><Surface className="p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">Your creator card</h2><p className="mt-1 text-xs text-[var(--muted)]">This is how brands discover your positioning and collaboration offer.</p></div><div className="flex shrink-0 flex-col gap-2"><SecondaryButton onClick={() => onNavigate("profile")} className="min-h-8 px-3 text-[10px]"><Eye size={12} /> Open card</SecondaryButton><CopyAction text="naano.com/creator/devesh" className="min-h-8 px-3 text-[10px]"><Copy size={12} /> Copy card link</CopyAction><CopyAction text="naano.com/creator/devesh" className="min-h-8 px-3 text-[10px]"><Share2 size={12} /> Share my card</CopyAction></div></div><div className="mt-5 flex justify-center"><CreatorCard data={card} compact /></div></Surface><Surface className="min-h-[310px] p-5"><div className="flex items-start justify-between"><div><h2 className="font-semibold">Your launch guide</h2><p className="mt-1 text-xs text-[var(--muted)]">1 of 1 steps complete</p></div><button onClick={() => onNavigate("profile")} className="text-xs font-semibold text-[var(--blue)]">Open card</button></div><div className="mt-10 flex items-center gap-4"><span className="grid h-7 w-7 place-items-center rounded-full bg-[#daf6e7] text-[#159358]"><CheckIcon /></span><div><p className="text-sm font-semibold">Card and price ready</p><p className="mt-1 text-xs text-[var(--muted)]">Your positioning and offer are ready to review.</p></div><StatusPill tone="green">Complete</StatusPill><button onClick={() => onNavigate("profile")} aria-label="Open creator card" className="ml-auto rounded-lg border border-[var(--line)] p-2"><ChevronRight size={15} /></button></div></Surface></div><div className="mt-4 grid gap-4 xl:grid-cols-2"><Surface className="p-5"><SectionHeader title="Recommended opportunities" action="Explore" onAction={() => onNavigate("opportunities")} /><MiniOpportunity name="Premium Inboxes" detail="Main campaign · strong match" /><MiniOpportunity name="OrbiSearch" detail="Main campaign · strong match" /></Surface><Surface className="p-5"><SectionHeader title="Active collaborations" action="See all" onAction={() => onNavigate("collabs")} /><div className="mt-6 text-center text-xs text-[var(--muted)]">No active collaborations.</div></Surface></div></>;
}

function ProfilePage({ card }: { card: CreatorCardData }) { return <><PageIntro title="Your Naano card, ready to travel." description="Share clear proof of your positioning, audience and offers. Every improvement makes the card more useful to brands." action={<div className="flex flex-wrap gap-2"><SecondaryButton onClick={() => document.getElementById("creator-card-preview")?.scrollIntoView({ behavior: "smooth", block: "center" })}>Preview</SecondaryButton><CopyAction text="naano.com/creator/devesh">Copy card link</CopyAction></div>} /><Surface className="sky-panel min-h-[365px] p-6 sm:p-9"><div className="relative z-10 max-w-[600px]"><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-[#4d7694]">Your card is your deal link</p><h2 className="mt-4 max-w-[540px] text-[29px] font-semibold leading-[1.08] tracking-[-.055em]">Put it on LinkedIn. Earn when a brand joins through it.</h2><p className="mt-4 max-w-[560px] text-sm leading-6 text-[var(--muted)]">Your public card presents your profile and keeps you selected when a brand creates its account.</p><div className="mt-6 flex flex-wrap gap-3"><InfoCard title="Add it as a LinkedIn experience" text="Keep your card visible on your profile so brands can discover and book you." /><InfoCard title="Send it when a brand contacts you" text="Share your card so the deal runs through Naano." /></div><CopyAction text="naano.com/creator/devesh" className="mt-6 bg-[#1f2024] hover:bg-[#303238]"><Share2 size={15} /> Copy or share my Deal Link</CopyAction></div><div className="absolute right-10 top-32 hidden w-40 sm:block"><p className="text-[10px] uppercase tracking-[.14em] text-[var(--muted)]">Your share</p><p className="mt-1 text-4xl font-bold">25%</p><hr className="my-4 border-[var(--line)]" /><p className="text-[10px] uppercase tracking-[.14em] text-[var(--muted)]">Reward period</p><p className="mt-3 text-sm font-semibold">3 months</p></div></Surface><div id="creator-card-preview" className="mt-8 flex scroll-mt-24 justify-center"><CreatorCard data={card} /></div></>; }

function OpportunitiesPage() { const [query, setQuery] = useState(""); const [industry, setIndustry] = useState("All industries"); const [country, setCountry] = useState("All countries"); const filtered = opportunities.filter((item) => item.name.toLowerCase().includes(query.toLowerCase()) && (industry === "All industries" || item.industry === industry) && (country === "All countries" || item.region.includes(country))); return <><PageIntro title="Opportunities" description="Open brand campaigns — apply, the brand accepts, and the booking is created on your terms." /><div className="flex gap-2"><StatusPill>All channels 2</StatusPill><StatusPill tone="gray">in LinkedIn 2</StatusPill></div><div className="mt-5 flex flex-col gap-2 xl:flex-row"><label className="flex h-10 flex-1 items-center gap-2 rounded-xl border border-[var(--line-strong)] bg-white px-3"><Search size={15} className="text-[var(--subtle)]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search for a campaign or a brand..." className="w-full bg-transparent text-sm outline-none" /></label><select value={industry} onChange={(event) => setIndustry(event.target.value)} className="h-10 rounded-xl border border-[var(--line-strong)] bg-white px-3 text-sm"><option>All industries</option><option>Software</option><option>Productivity</option><option>AI</option></select><select value={country} onChange={(event) => setCountry(event.target.value)} className="h-10 rounded-xl border border-[var(--line-strong)] bg-white px-3 text-sm"><option>All countries</option><option>Europe</option><option>North America</option></select><select className="h-10 rounded-xl border border-[var(--line-strong)] bg-white px-3 text-sm"><option>Relevance (default)</option><option>Deadline soonest</option></select></div><div className="mt-5 grid max-w-[720px] gap-4 sm:grid-cols-2">{filtered.length ? filtered.map((item) => <CampaignCard key={item.name} {...item} />) : <Surface className="col-span-full p-10 text-center text-sm text-[var(--muted)]">No opportunities match your search. Try a different campaign or clear the filters.</Surface>}</div></>; }

function CollaborationsPage() { const tabs = ["All", "Active", "Needs action", "Applications sent", "Declined", "Completed"]; const [active, setActive] = useState("All"); return <><PageIntro title="Collaborations" description="Every step tells you where you stand, what to do, and what happens if you do nothing." /><div className="flex gap-5 overflow-x-auto border-b border-[var(--line)] pb-3 text-xs font-semibold text-[var(--muted)]">{tabs.map((tab) => <button key={tab} onClick={() => setActive(tab)} className={`shrink-0 border-b-2 pb-3 ${active === tab ? "border-[var(--blue)] text-[var(--blue)]" : "border-transparent"}`}>{tab} <b className={`ml-1 rounded-full px-1.5 ${active === tab ? "bg-[var(--blue)] text-white" : "bg-[#f1f3f6] text-[var(--muted)]"}`}>0</b></button>)}</div><Surface className="mt-4 overflow-hidden"><div className="hidden grid-cols-6 border-b border-[var(--line)] px-5 py-4 text-[10px] font-semibold uppercase tracking-wide text-[var(--muted)] sm:grid"><span>Brand</span><span>Campaign</span><span>Status</span><span>Performance</span><span>Next action</span><span>Your net</span></div><div className="py-16 text-center text-xs text-[var(--muted)]">No {active.toLowerCase() === "all" ? "collaborations" : active.toLowerCase()} yet. Brand invitations and accepted applications will land here.</div><div className="border-t border-[var(--line)] px-5 py-4 text-xs text-[var(--muted)]">0 collaborations</div></Surface></>; }

function AnalyticsPage() { return <><PageIntro title="Analytics" description="Public LinkedIn performance imported for this profile." action={<select className="rounded-xl border border-[var(--line-strong)] bg-white px-4 py-2 text-sm"><option>All time</option><option>Last 30 days</option></select>} /><Surface className="sky-panel p-5 sm:p-7"><div className="relative z-10 flex flex-col justify-between gap-4 sm:flex-row"><div><StatusPill tone="green">Public LinkedIn snapshot</StatusPill><h2 className="mt-4 text-2xl font-semibold tracking-[-.04em]">Public LinkedIn posts are being imported</h2><p className="mt-2 text-sm text-[var(--muted)]">The profile is ready. Post history and reach will appear after the public-data job completes.</p></div><div className="sm:border-l sm:border-[var(--line)] sm:pl-8"><p className="text-3xl font-bold">0%</p><p className="text-xs text-[var(--muted)]">of imported posts include reach data</p><StatusPill tone="green">Import in progress</StatusPill></div></div></Surface><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Public posts" value="0" detail="Original LinkedIn posts found" /><StatCard label="Public post reach" value="Pending" detail="Waiting for public post data" /><StatCard label="Public engagements" value="0" detail="Reactions, comments and reposts" /><StatCard label="LinkedIn followers" value="1,027" detail="Imported from the public profile" /></div><div className="mt-4 grid gap-4 xl:grid-cols-[1.5fr_1fr]"><Surface className="min-h-[210px] p-5"><SectionHeader title="Recent LinkedIn posts" action="" /><div className="grid h-36 place-items-center text-center text-xs text-[var(--muted)]"><div><b>Public post import in progress</b><p className="mt-2">The first public LinkedIn posts will appear here automatically.</p></div></div></Surface><Surface className="p-5"><SectionHeader title="Public profile summary" action="" /><SummaryRow label="LinkedIn followers" value="1,027" /><SummaryRow label="Public posts" value="0" /><SummaryRow label="Posts with reach data" value="0" /><SummaryRow label="Public engagements" value="0" /></Surface></div></>; }

function CommunityPage({ card }: { card: CreatorCardData }) { return <><PageIntro title="Community" description="Learn with other B2B creators, share what works and make your Naano identity visible." action={<StatusPill tone="green">Creator network</StatusPill>} /><div className="grid gap-4 xl:grid-cols-2"><Surface className="sky-panel min-h-[360px] p-6"><div className="relative z-10"><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-[var(--muted)]">Naano creators on Slack</p><h2 className="mt-3 text-xl font-semibold">The room where B2B creators get better together.</h2><p className="mt-2 max-w-[480px] text-sm leading-6 text-[var(--muted)]">Ask for feedback on a sponsored post, compare campaign lessons, meet creators and help shape what Naano builds next.</p><ul className="mt-6 space-y-3 text-xs text-[#50617e]"><li>✓ Get feedback before you publish</li><li>✓ Share campaign tips that work</li><li>✓ Talk directly with the Naano team</li></ul><MockActionButton className="mt-8" successText="Slack invite copied"><span className="mr-2">✣</span> Join the Slack community</MockActionButton></div></Surface><Surface className="p-6"><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-[var(--muted)]">LinkedIn visibility</p><h2 className="mt-3 text-xl font-semibold">Turn your LinkedIn profile into an always-on Deal Link</h2><div className="mt-5 rounded-xl border border-[#cde0eb] bg-[#eefaff] p-4"><b>25%</b><p className="text-xs text-[var(--muted)]">of Naano’s commission for 3 months</p></div><div className="mt-5 flex justify-center"><CreatorCard data={card} compact /></div><MockActionButton className="mt-5 w-full" successText="Card published"><Share2 size={15} /> Publish my card <ArrowIcon /></MockActionButton></Surface></div></>; }

function EarningsPage() { return <><PageIntro title="Earnings" description="Track revenue from your paid collaborations and withdraw available funds." action={<StatusPill>Paid collaborations</StatusPill>} /><div className="grid gap-3 xl:grid-cols-3"><StatCard label="Total earned" value="€0" detail="0 paid collaborations · €0 average" /><StatCard label="In transit" value="€0" detail="International transfers usually arrive within 1–7 days" /><StatCard label="Available now" value="€0" detail="Ready to withdraw to your selected payout method" /></div><div className="mt-4 grid gap-4 xl:grid-cols-[1.4fr_1fr]"><Surface className="p-5"><SectionHeader title="Earnings over time" action="€0 over 6 months" /><div className="mt-8 flex h-36 items-end gap-2">{["Apr", "May", "Jun", "Jul", "Aug", "Sept"].map((month, index) => <div key={month} className={`flex flex-1 flex-col justify-end rounded-t-lg border-b-4 border-[var(--blue)] bg-[#f1f4f9] ${index === 5 ? "bg-[#e9efff]" : ""}`}><span className="mb-2 text-center text-[9px] text-[var(--muted)]">€0</span><span className="mt-auto pb-[-1px] text-center text-[9px] text-[var(--muted)]">{month}</span></div>)}</div></Surface><Surface className="p-5"><SectionHeader title="Withdraw earnings" action="" /><p className="mt-4 text-[10px] font-semibold uppercase tracking-wide text-[var(--muted)]">Payout method</p><div className="mt-2 rounded-xl border border-[var(--line)] p-3 text-sm">◯ Bank transfer<p className="mt-1 text-xs text-[var(--muted)]">No account holder on file</p></div><div className="mt-2 rounded-xl border border-[var(--blue)] bg-[var(--blue-soft)] p-3 text-sm">◉ Stripe<p className="mt-1 text-xs text-[var(--muted)]">Status: Not connected</p><MockActionButton className="mt-2 min-h-8 px-3 text-xs" successText="Demo only">Connect Stripe</MockActionButton></div><PrimaryButton disabled className="mt-3 w-full">Confirm withdrawal</PrimaryButton></Surface></div></>; }

function ReferralsPage() { return <><div className="mx-auto max-w-[800px] py-8 text-center sm:py-12"><StatusPill>Creator affiliation · 25% for 3 months</StatusPill><h1 className="mt-8 text-4xl font-semibold tracking-[-.07em] sm:text-5xl">Recommend Naano. Earn for 3 months.</h1><p className="mx-auto mt-5 max-w-[540px] text-sm leading-6 text-[var(--muted)]">Share your personal link with a company. If it joins Naano and launches paid campaigns, you receive 25% of Naano’s commission for three months.</p><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><CopyAction text="naano.com/invite/you"><Copy size={15} /> Copy my referral link</CopyAction><MockActionButton successText="Guide opened">See how it works <ArrowIcon /></MockActionButton></div><Surface className="sky-panel mt-12 p-5 text-left sm:p-7"><div className="relative z-10 grid gap-8 sm:grid-cols-2"><div><p className="text-[10px] uppercase tracking-[.14em] text-[var(--muted)]">Introduce a company to Naano</p><p className="mt-4 rounded-xl border border-[var(--line)] bg-white p-4 text-sm">naano.com/invite/you <span className="float-right text-[var(--green)]">✓</span></p></div><div><p className="text-[10px] uppercase tracking-[.14em] text-[var(--muted)]">Your share of Naano’s commission</p><p className="mt-3 text-3xl font-bold">25%</p><hr className="my-3 border-[var(--line)]" /><p className="text-xs text-[var(--muted)]">Reward period <b className="float-right text-[var(--ink)]">3 months</b></p></div></div></Surface></div></>; }

function MessagesPage() { return <><PageIntro title="Messages" description="Ask for help, get product guidance, and keep your Naano work moving." /><div className="grid min-h-[600px] overflow-hidden rounded-2xl border border-[var(--line)] bg-white lg:grid-cols-[240px_1fr]"><aside className="border-b border-[var(--line)] p-4 lg:border-b-0 lg:border-r"><h2 className="text-lg font-semibold">Messages</h2><label className="mt-4 flex h-9 items-center gap-2 rounded-lg border border-[var(--line)] px-2"><Search size={14} className="text-[var(--subtle)]" /><input placeholder="Search conversations" className="w-full text-xs outline-none" /></label><div className="mt-4 rounded-lg bg-[var(--blue-soft)] p-3 text-xs font-semibold">NaanoBot<p className="mt-1 font-normal text-[var(--muted)]">A question or need help? Start here.</p></div></aside><div className="flex flex-col"><div className="border-b border-[var(--line)] p-4 text-sm font-semibold"><BrandSymbol /> Naano help center</div><div className="flex-1 p-6"><Surface className="sky-panel mx-auto max-w-[560px] p-5"><p className="text-[10px] uppercase tracking-[.14em] text-[var(--muted)]">Your Naano space</p><h2 className="mt-3 text-xl font-semibold">How can we help?</h2><p className="mt-2 text-sm text-[var(--muted)]">Product question, bug or performance concern: everything stays here and the team steps in when needed.</p><div className="mt-5 grid gap-2 sm:grid-cols-2"><MockActionButton className="justify-start text-xs" successText="Ready to help">Understand my performance</MockActionButton><MockActionButton className="justify-start text-xs" successText="Ready to help">Get product help</MockActionButton><MockActionButton className="justify-start text-xs" successText="Ready to help">Report a bug</MockActionButton><MockActionButton className="justify-start text-xs" successText="Ready to help">Suggest an idea</MockActionButton></div></Surface></div><MessageComposer /></div></div></>; }

function CampaignCard({ name, match, region, deadline, logo, industry }: { name: string; match: string; region: string; deadline: string; logo: string; industry: string }) { return <Surface className="overflow-hidden p-3"><div className="relative h-20 rounded-xl bg-gradient-to-br from-[#e5f0ff] via-white to-[#f3f7ff]"><span className="absolute left-2 top-2 rounded-full bg-white px-2 py-1 text-[9px] font-semibold">in LinkedIn</span><span className="absolute right-2 top-2 rounded-full bg-white px-2 py-1 text-[9px] text-[var(--blue)]">● {match}</span><div className="absolute -bottom-5 left-1/2 grid h-12 w-12 -translate-x-1/2 place-items-center rounded-xl border-4 border-white bg-[#20242d] text-lg font-bold text-white shadow-sm">{logo}</div></div><h3 className="mt-8 text-center text-sm font-semibold">{name}</h3><p className="mt-1 text-center text-[10px] text-[var(--muted)]">Main campaign · {industry}</p><p className="mx-auto mt-3 w-fit rounded-full bg-[#f6f8fb] px-2 py-1 text-[9px] text-[var(--muted)]">◉ {region}</p><div className="mt-4 rounded-xl border border-[var(--line)] bg-[#fbfcfe] p-2 text-center text-[10px] text-[var(--muted)]">Audience relevance <b className="float-right text-[var(--blue)]">100/100</b><div className="mt-2 h-1 rounded-full bg-[var(--blue)]" /></div><div className="mt-3 grid grid-cols-3 border-y border-[var(--line)] py-2 text-center text-[10px]"><b>100/100<span className="block text-[8px] font-normal text-[var(--muted)]">MATCH</span></b><b>LinkedIn<span className="block text-[8px] font-normal text-[var(--muted)]">CHANNEL</span></b><b>{deadline}<span className="block text-[8px] font-normal text-[var(--muted)]">POST DEADLINE</span></b></div><div className="mt-3 grid grid-cols-2 gap-2"><MockActionButton className="min-h-9 px-2 text-xs" successText="Brief opened">View the brief</MockActionButton><MockActionButton className="min-h-9 px-2 text-xs" successText="Application saved">Apply</MockActionButton></div></Surface>; }

function StatCard({ label, value, detail }: { label: string; value: string; detail: string }) { return <Surface className="p-4"><p className="text-[10px] font-semibold uppercase tracking-wide text-[var(--muted)]">{label}</p><p className="mt-5 text-2xl font-bold tracking-[-.05em]">{value}</p><p className="mt-1 text-[10px] text-[var(--muted)]">{detail}</p></Surface>; }
function InfoCard({ title, text }: { title: string; text: string }) { return <div className="w-full max-w-[260px] rounded-xl bg-white/80 p-4"><p className="text-sm font-semibold">{title}</p><p className="mt-1 text-xs leading-5 text-[var(--muted)]">{text}</p></div>; }
function SectionHeader({ title, action, onAction }: { title: string; action: React.ReactNode; onAction?: () => void }) { return <div className="flex items-center justify-between"><div><h2 className="font-semibold">{title}</h2>{action && <p className="mt-1 text-[10px] text-[var(--muted)]">{action}</p>}</div>{typeof action === "string" && action && <button onClick={onAction} className="text-xs font-semibold text-[var(--blue)]">{action}</button>}</div>; }
function MiniOpportunity({ name, detail }: { name: string; detail: string }) { return <div className="mt-4 flex items-center gap-3 border-t border-[var(--line)] pt-3 text-xs"><span className="grid h-7 w-7 place-items-center rounded-lg bg-[#20242d] text-[10px] font-bold text-white">{name === "Premium Inboxes" ? "PI" : "o"}</span><span><b>{name}</b><span className="block text-[10px] text-[var(--muted)]">{detail}</span></span><ChevronRight size={14} className="ml-auto text-[var(--blue)]" /></div>; }
function SummaryRow({ label, value }: { label: string; value: string }) { return <div className="mt-4"><div className="flex justify-between text-xs"><span className="text-[var(--muted)]">{label}</span><b>{value}</b></div><div className="mt-2 h-1 rounded-full bg-[#e9edf3]"><div className="h-1 w-1/3 rounded-full bg-[#9db4ff]" /></div></div>; }
function CopyAction({ text, children, className = "" }: { text: string; children: React.ReactNode; className?: string }) { const [copied, setCopied] = useState(false); const copy = async () => { try { await navigator.clipboard?.writeText(text); } finally { setCopied(true); window.setTimeout(() => setCopied(false), 1600); } }; return <PrimaryButton onClick={copy} className={className}>{copied ? "Copied" : children}</PrimaryButton>; }
function MockActionButton({ children, successText, className = "" }: { children: React.ReactNode; successText: string; className?: string }) { const [done, setDone] = useState(false); return <SecondaryButton onClick={() => setDone(true)} className={className}>{done ? `✓ ${successText}` : children}</SecondaryButton>; }
function MessageComposer() { const [draft, setDraft] = useState(""); const [sent, setSent] = useState(false); const send = () => { if (!draft.trim()) return; setSent(true); setDraft(""); }; return <div className="flex gap-2 border-t border-[var(--line)] p-3"><input value={draft} onChange={(event) => { setDraft(event.target.value); setSent(false); }} onKeyDown={(event) => { if (event.key === "Enter") send(); }} placeholder="Ask Naano a question..." className="min-w-0 flex-1 rounded-xl border border-[var(--line)] px-4 text-sm outline-none" /><PrimaryButton onClick={send} aria-label="Send message" disabled={!draft.trim()}>{sent ? "✓" : "→"}</PrimaryButton></div>; }
function AssistantBar() { return <div className="fixed bottom-4 left-1/2 z-20 flex w-[min(340px,calc(100%-32px))] -translate-x-1/2 items-center justify-between rounded-full border border-[#e4e8ee] bg-white/95 p-1.5 pl-4 shadow-[0_8px_28px_rgba(25,36,64,.12)] backdrop-blur"><span className="flex items-center gap-3 text-sm text-[#9aa1aa]"><SparkleIcon /> What would you like to see?</span><span className="grid h-9 w-9 place-items-center rounded-full bg-[#f1f2f4] text-[#9aa1aa]">⌁</span></div>; }
function TourOverlay({ section, onClose, onNavigate }: { section: NavSection; onClose: () => void; onNavigate: (id: NavSection) => void }) { const order: NavSection[] = ["profile", "home", "opportunities", "collabs", "analytics"]; const index = Math.max(0, order.indexOf(section)); const labels = ["Your Marketplace card", "Your creator overview", "Find opportunities", "Manage collaborations", "Track your performance"]; return <div className="fixed inset-0 z-40 bg-[#172033]/35"><div className="fixed bottom-5 right-5 w-[390px] rounded-2xl border border-[#d5dff0] bg-white p-6 shadow-2xl"><div className="flex justify-between text-[10px] font-semibold text-[var(--muted)]"><span>STEP {index + 1} OF 5</span><button onClick={onClose}>Skip</button></div><h2 className="mt-5 text-lg font-semibold">{labels[index]}</h2><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{index === 0 ? "This is your private preview and editor. Keep your positioning, packs and price clear before sharing your card." : "Start here to see your card, priority actions and active collaborations at a glance."}</p><div className="mt-5 flex items-center gap-1">{order.map((_, dot) => <span key={dot} className={`h-1.5 w-5 rounded-full ${dot === index ? "bg-[var(--blue)]" : "bg-[#dce3ef]"}`} />)}</div><div className="mt-5 flex justify-end gap-2">{index > 0 && <SecondaryButton onClick={() => onNavigate(order[index - 1])} className="min-h-9 px-4 text-xs">Back</SecondaryButton>}<PrimaryButton onClick={() => index === order.length - 1 ? onClose() : onNavigate(order[index + 1])} className="min-h-9 px-4 text-xs">{index === order.length - 1 ? "Finish" : "Next"}</PrimaryButton></div></div></div>; }
function CheckIcon() { return <span className="text-xs">✓</span>; }
function ArrowIcon() { return <ArrowRight size={14} />; }
function SparkleIcon() { return <span className="text-lg text-[#8d9095]">✣</span>; }
