import Link from "next/link";
import { ArrowRight, Check, CirclePlay, Handshake, Layers3, MessageCircle, Sparkles, Users } from "lucide-react";
import { BrandSymbol } from "@/components/creator-card";
import { PrimaryButton, SecondaryButton, StatusPill } from "@/components/ui";

const benefits = [
  "Creator cards built for B2B buyers",
  "Campaigns that become real opportunities",
  "One shared place for applications and messages",
];

export function LandingPage() {
  return <main className="min-h-screen overflow-hidden bg-[#f7f9fc] text-[var(--ink)]">
    <header className="mx-auto flex h-20 max-w-[1180px] items-center justify-between px-5 sm:px-8">
      <Link href="/" className="brand-mark text-xl"><BrandSymbol /> naano</Link>
      <nav className="hidden items-center gap-7 text-sm font-semibold text-[var(--muted)] md:flex"><a href="#how-it-works">How it works</a><a href="#for-you">For creators</a><a href="#for-you">For brands</a></nav>
      <div className="flex items-center gap-2"><Link href="/signin" className="hidden px-3 py-2 text-sm font-semibold text-[var(--ink)] sm:block">Sign in</Link><Link href="/onboarding"><PrimaryButton className="min-h-9 px-4 text-xs">Get started <ArrowRight size={14} /></PrimaryButton></Link></div>
    </header>

    <section className="relative mx-auto grid max-w-[1180px] gap-12 px-5 pb-20 pt-12 sm:px-8 md:grid-cols-[1.05fr_.95fr] md:items-center md:pt-20 lg:pb-28">
      <div className="absolute -left-48 top-0 -z-0 h-[480px] w-[480px] rounded-full bg-[#dce7ff]/70 blur-3xl" />
      <div className="relative z-10"><StatusPill>Built for B2B creator marketing</StatusPill><h1 className="mt-6 max-w-[680px] text-4xl font-bold leading-[.98] tracking-[-.07em] sm:text-5xl lg:text-6xl">The creator marketplace for work that deserves trust.</h1><p className="mt-6 max-w-[570px] text-base leading-7 text-[var(--muted)] sm:text-lg">Naano brings brands and credible LinkedIn creators together—from a clear brief and application to an active collaboration.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/onboarding?role=brand"><PrimaryButton className="w-full sm:w-auto">I&apos;m a brand <ArrowRight size={16} /></PrimaryButton></Link><Link href="/onboarding?role=creator"><SecondaryButton className="w-full sm:w-auto">I&apos;m a creator</SecondaryButton></Link></div><div className="mt-8 space-y-3">{benefits.map((benefit) => <p key={benefit} className="flex items-center gap-3 text-sm font-medium"><span className="grid h-5 w-5 place-items-center rounded-full bg-[#e8f8ef] text-[#159358]"><Check size={12} /></span>{benefit}</p>)}</div></div>
      <div className="relative z-10 mx-auto w-full max-w-[500px]"><div className="absolute -right-10 top-8 h-40 w-40 rounded-full bg-[#b9d4ff]/70 blur-3xl" /><div className="relative overflow-hidden rounded-[28px] border border-[#d7e2f4] bg-white p-4 shadow-[0_30px_70px_rgba(42,69,129,.15)] sm:p-5"><div className="sky-panel rounded-2xl p-5"><div className="flex items-center justify-between"><span className="brand-mark text-base"><BrandSymbol /> naano</span><span className="rounded-full bg-white px-3 py-1 text-[10px] font-semibold text-[#159358] shadow-sm">● Campaign live</span></div><p className="mt-10 text-[10px] font-semibold uppercase tracking-[.16em] text-[#4c7199]">Creator opportunity</p><h2 className="mt-2 max-w-[290px] text-2xl font-bold leading-tight tracking-[-.05em]">Bring trusted DevOps stories to the people who build.</h2><p className="mt-3 text-sm leading-6 text-[var(--muted)]">A campaign brief matched to proven B2B voices.</p></div><div className="mt-4 grid gap-3 sm:grid-cols-[1fr_auto]"><div className="rounded-2xl border border-[var(--line)] p-4"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-gradient-to-br from-[#43588f] to-[#b6968a] text-xs font-bold text-white">DR</span><span><b className="block text-sm">Devesh Rathod</b><span className="text-xs text-[var(--muted)]">AI · Productivity · Software</span></span></div><div className="mt-4 flex items-center justify-between border-t border-[var(--line)] pt-3 text-xs"><span className="text-[var(--muted)]">Starting at</span><b className="text-base">€300 / post</b></div></div><div className="flex items-center justify-center rounded-2xl bg-[#edf2ff] p-4 text-center text-[var(--blue)]"><span><Handshake className="mx-auto" size={23} /><b className="mt-2 block text-xs">A clearer way<br />to collaborate</b></span></div></div></div></div>
    </section>

    <section className="border-y border-[#e1e7f0] bg-white/70"><div className="mx-auto grid max-w-[1180px] gap-6 px-5 py-6 sm:grid-cols-3 sm:px-8"><TrustItem value="One workspace" label="for briefs, applications, and messages" /><TrustItem value="Creator-led" label="built around credible professional voices" /><TrustItem value="Clear terms" label="before a collaboration begins" /></div></section>

    <section id="for-you" className="border-y border-[#e1e7f0] bg-white"><div className="mx-auto grid max-w-[1180px] gap-5 px-5 py-16 sm:px-8 md:grid-cols-2"><RoleCard icon={Sparkles} eyebrow="For creators" title="Make your expertise easy to choose." text="Build a useful card, discover campaigns that fit, apply on your terms, and keep every collaboration in one workspace." cta="Build my creator card" href="/onboarding?role=creator" /><RoleCard icon={Layers3} eyebrow="For brands" title="Find the voices your buyers already trust." text="Create a focused brief, meet relevant creators, review applications, and keep your campaign decisions connected." cta="Launch a campaign" href="/onboarding?role=brand" dark /></div></section>

    <section id="how-it-works" className="mx-auto max-w-[1180px] px-5 py-20 sm:px-8"><div className="max-w-[620px]"><StatusPill tone="gray">One calm workflow</StatusPill><h2 className="mt-5 text-3xl font-bold tracking-[-.06em] sm:text-4xl">From the right brief to the right collaboration.</h2></div><div className="mt-10 grid gap-5 md:grid-cols-3"><Step number="01" icon={Users} title="Set up your side" text="Create a creator card or give your brand the context it needs for better matches." /><Step number="02" icon={Layers3} title="Find the fit" text="Brands publish opportunities; creators browse, ask questions, and apply." /><Step number="03" icon={MessageCircle} title="Work in one thread" text="Accepted applications open a shared conversation for campaign details and delivery." /></div></section>

    <section className="mx-5 mb-10 overflow-hidden rounded-[28px] bg-[#172b68] text-white sm:mx-8"><div className="mx-auto flex max-w-[1180px] flex-col gap-8 px-6 py-12 sm:px-10 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.16em] text-[#a9c4ff]">Ready when you are</p><h2 className="mt-3 max-w-[600px] text-3xl font-bold tracking-[-.06em] sm:text-4xl">Start with a real workspace, not another pitch deck.</h2></div><div className="flex flex-col gap-3 sm:flex-row"><Link href="/demo"><SecondaryButton className="w-full border-white/30 bg-white/10 text-white hover:bg-white/20 sm:w-auto"><CirclePlay size={16} /> View demo</SecondaryButton></Link><Link href="/onboarding"><PrimaryButton className="w-full bg-white text-[#17306f] hover:bg-[#edf2ff] sm:w-auto">Create an account <ArrowRight size={16} /></PrimaryButton></Link></div></div></section>
  </main>;
}

function RoleCard({ icon: Icon, eyebrow, title, text, cta, href, dark = false }: { icon: typeof Sparkles; eyebrow: string; title: string; text: string; cta: string; href: string; dark?: boolean }) {
  return <article className={`rounded-3xl p-6 sm:p-8 ${dark ? "bg-[#1b387d] text-white" : "border border-[var(--line)] bg-[#f8faff]"}`}><span className={`grid h-11 w-11 place-items-center rounded-2xl ${dark ? "bg-white/15 text-white" : "bg-[#e7efff] text-[var(--blue)]"}`}><Icon size={21} /></span><p className={`mt-7 text-xs font-semibold uppercase tracking-[.16em] ${dark ? "text-[#a9c4ff]" : "text-[var(--blue)]"}`}>{eyebrow}</p><h3 className="mt-3 text-2xl font-bold tracking-[-.05em]">{title}</h3><p className={`mt-4 max-w-[460px] text-sm leading-6 ${dark ? "text-[#d6e0ff]" : "text-[var(--muted)]"}`}>{text}</p><Link href={href} className={`mt-7 inline-flex items-center gap-2 text-sm font-semibold ${dark ? "text-white" : "text-[var(--blue)]"}`}>{cta} <ArrowRight size={15} /></Link></article>;
}

function Step({ number, icon: Icon, title, text }: { number: string; icon: typeof Users; title: string; text: string }) {
  return <article className="rounded-2xl border border-[var(--line)] bg-white p-6"><div className="flex items-center justify-between"><span className="text-xs font-bold tracking-[.14em] text-[var(--blue)]">{number}</span><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#eef3ff] text-[var(--blue)]"><Icon size={18} /></span></div><h3 className="mt-8 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">{text}</p></article>;
}

function TrustItem({ value, label }: { value: string; label: string }) {
  return <div className="border-l-2 border-[#d6e2ff] pl-4"><p className="text-sm font-bold tracking-[-.02em]">{value}</p><p className="mt-1 text-xs leading-5 text-[var(--muted)]">{label}</p></div>;
}
