import Link from "next/link";
import { ArrowRight, Check, ChevronDown, Globe2, Linkedin, Play, ShieldCheck, Sparkles, UsersRound } from "lucide-react";
import { BrandSymbol } from "@/components/creator-card";

const navItems = [
  ["For companies", "#companies"],
  ["For creators", "#creators"],
  ["For agencies", "#agencies"],
  ["How it works", "#how-it-works"],
] as const;

const logos = ["a Growth Machine", "gojiberry", "ChatSEO", "Abyssale", "BlogSEO", "lemlist", "folk"];

export function LandingPage() {
  return (
    <main className="overflow-hidden bg-[#f8fafc] text-[#17191f]">
      <header className="sticky top-0 z-30 border-b border-black/[.035] bg-white/92 backdrop-blur-md">
        <div className="mx-auto flex h-[86px] max-w-[1920px] items-center justify-between px-6 sm:px-10 lg:px-14">
          <Link href="/" aria-label="Naano home" className="brand-mark text-[30px] font-extrabold text-[#0d1118] sm:text-[32px]"><BrandSymbol /> naano</Link>
          <nav aria-label="Primary" className="hidden items-center gap-9 text-[17px] font-medium tracking-[-.025em] lg:flex">
            {navItems.map(([label, href]) => <a key={label} href={href} className="hover:text-[#315ef5]">{label}</a>)}
            <a href="#agencies" className="inline-flex items-center gap-1 hover:text-[#315ef5]">Resources <ChevronDown size={14} strokeWidth={2.4} /></a>
          </nav>
          <div className="flex items-center gap-2 sm:gap-3">
            <button type="button" aria-label="Language" className="hidden items-center gap-2 px-2 py-2 text-sm font-semibold sm:inline-flex"><Globe2 size={17} strokeWidth={1.8} /> EN</button>
            <Link href="/signin" className="rounded-full border border-[#e9e5df] bg-white px-4 py-2.5 text-sm font-semibold shadow-[0_2px_8px_rgba(19,29,53,.03)] transition hover:border-[#ccd5e8] hover:bg-[#f8faff] sm:px-5 sm:text-base">Sign in</Link>
            <Link href="/onboarding" className="rounded-full bg-[#171a20] px-4 py-2.5 text-sm font-semibold text-white transition hover:-translate-y-px hover:bg-[#315ef5] sm:px-5 sm:text-base">Sign up</Link>
          </div>
        </div>
      </header>

      <section className="relative isolate flex min-h-[calc(100svh-86px)] items-center overflow-hidden bg-[#d9f3ff] px-5 py-20 sm:px-8 lg:px-12">
        <div className="absolute inset-0 -z-20 bg-cover bg-center bg-no-repeat" style={{ backgroundImage: "url('/naano-cloud-hero.png')" }} />
        <div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_50%_35%,rgba(237,251,255,.25),rgba(239,250,255,.06)_37%,rgba(222,247,255,.2)_100%)]" />
        <div className="relative mx-auto flex w-full max-w-[1210px] flex-col items-center text-center">
          <div className="inline-flex items-center gap-3 rounded-full bg-white/90 px-4 py-2 text-sm font-medium tracking-[-.01em] text-[#363a42] shadow-[0_10px_30px_rgba(69,123,163,.12)] sm:text-base">
            <span className="text-[18px] leading-none">𝕏</span><span className="h-5 w-px bg-[#dfe4e9]" /><Linkedin size={20} fill="#1769aa" className="text-[#1769aa]" />
            <span>Where B2B brands work with creators</span>
          </div>
          <h1 className="mt-12 max-w-[980px] text-[48px] font-semibold leading-[.94] tracking-[-.075em] text-[#17191f] sm:text-[72px] md:text-[92px] lg:text-[104px]">The B2B LinkedIn<br className="hidden sm:block" /> Creator Marketplace.</h1>
          <p className="mt-9 max-w-[770px] text-[19px] leading-[1.42] tracking-[-.025em] text-[#454b55] sm:text-[24px] lg:text-[27px]">Find the creators your buyers already trust, launch campaigns in days, and track the clicks, leads and pipeline generated by every post.</p>
          <div className="mt-11 flex flex-col items-center justify-center gap-3 sm:flex-row sm:gap-8">
            <Link href="/onboarding?role=brand" className="inline-flex items-center gap-3 rounded-xl bg-[#1b1d22] px-7 py-4 text-[17px] font-semibold text-white shadow-[0_12px_24px_rgba(22,29,43,.2)] transition hover:-translate-y-0.5 hover:bg-[#315ef5]">Launch a campaign <ArrowRight size={20} /></Link>
            <a href="#how-it-works" className="inline-flex items-center gap-3 px-4 py-3 text-[17px] font-semibold transition hover:text-[#315ef5]">See how Naano works <ArrowRight size={20} /></a>
          </div>
          <p className="mt-10 inline-flex items-center gap-3 text-[15px] font-medium text-[#5d636d]"><ShieldCheck size={21} strokeWidth={1.6} /> Trusted by modern B2B teams</p>
        </div>
        <div aria-label="Trusted company logos" className="absolute inset-x-0 bottom-9 flex items-center justify-around gap-6 overflow-hidden px-5 text-center text-[15px] font-bold tracking-[-.04em] text-[#585d65]/70 sm:bottom-12 sm:text-[21px] lg:text-[24px]">
          {logos.map((logo, index) => <span key={logo} className={`${index > 4 ? "hidden lg:inline" : index > 3 ? "hidden md:inline" : ""} whitespace-nowrap`}>{logo}</span>)}
        </div>
      </section>

      <section id="companies" className="bg-[#fcfcfb] px-5 py-24 sm:px-8 sm:py-32">
        <div className="mx-auto max-w-[1100px] text-center">
          <p className="text-xs font-bold uppercase tracking-[.22em] text-[#315ef5]">The marketplace advantage</p>
          <h2 className="mx-auto mt-5 max-w-[850px] text-4xl font-semibold leading-[1.02] tracking-[-.065em] sm:text-6xl">One place to find trusted B2B voices and turn them into measurable momentum.</h2>
          <div className="mt-14 grid gap-4 text-left md:grid-cols-3">
            <Benefit icon={UsersRound} title="Find the credible voices" text="Discover creators who already reach the people your business needs to influence." />
            <Benefit icon={Sparkles} title="Launch with clarity" text="Create a focused brief, compare creator cards, and agree on the terms before work starts." />
            <Benefit icon={Check} title="See the outcome" text="Keep applications, campaign activity, and collaboration messages connected in one workspace." />
          </div>
        </div>
      </section>

      <section id="how-it-works" className="border-y border-[#ebe9e5] bg-[#f7f7f5] px-5 py-24 sm:px-8 sm:py-32">
        <div className="mx-auto grid max-w-[1180px] gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-center">
          <div><p className="text-xs font-bold uppercase tracking-[.22em] text-[#315ef5]">How it works</p><h2 className="mt-5 text-4xl font-semibold leading-[1.02] tracking-[-.065em] sm:text-6xl">B2B influence, without the spreadsheet chaos.</h2><p className="mt-7 max-w-[480px] text-lg leading-8 text-[#686f7b]">Naano gives brands and creators a shared path from an initial brief to a live collaboration.</p><Link href="/onboarding?role=creator" className="mt-8 inline-flex items-center gap-3 font-semibold text-[#315ef5]">Build your creator card <ArrowRight size={18} /></Link></div>
          <ol className="grid gap-3"><WorkflowStep number="01" title="Create your profile or brief" text="Give the marketplace the context it needs to make useful matches." /><WorkflowStep number="02" title="Choose the right fit" text="Creators can apply to opportunities; brands can review real creator cards." /><WorkflowStep number="03" title="Move the work forward" text="Accepted applications open a shared collaboration and message thread." /></ol>
        </div>
      </section>

      <section id="agencies" className="bg-[#fdfdfc] px-5 py-28 sm:px-8 sm:py-36">
        <div className="mx-auto max-w-[1120px] text-center">
          <p className="text-xs font-bold uppercase tracking-[.22em] text-[#315ef5]">Built for people who run influence</p>
          <blockquote className="mt-12 text-4xl font-medium leading-[1.12] tracking-[-.06em] text-[#202124] sm:text-5xl lg:text-[62px]">“We manage €10M+ of influence budget every year. For B2B, Naano simply makes our <span className="bg-gradient-to-r from-[#a6b4cb] to-[#c9d6ff] bg-clip-text text-transparent">life easier</span>.”</blockquote>
          <div className="mx-auto mt-12 grid h-28 w-28 place-items-center rounded-full bg-[radial-gradient(circle_at_40%_30%,#eed0af_0_12%,#3f5167_13%_34%,#1d2430_35%)] text-lg font-bold text-white shadow-[0_12px_25px_rgba(22,29,43,.16)]">DZ</div>
          <p className="mt-5 text-xl font-semibold tracking-[-.04em]">David Zmirov</p><p className="mt-1 text-lg text-[#6d737d]">CEO, Zmirov Communication</p><p className="mt-1 text-base text-[#a3a8b0]">Influence agency</p>
        </div>
      </section>

      <section id="creators" className="bg-[#171a20] px-5 py-20 text-white sm:px-8 sm:py-24">
        <div className="mx-auto flex max-w-[1180px] flex-col items-start justify-between gap-9 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-[#9ebaff]">For LinkedIn creators</p><h2 className="mt-5 max-w-[720px] text-4xl font-semibold leading-[1.02] tracking-[-.065em] sm:text-6xl">Build a creator card brands can confidently choose.</h2></div><div className="flex flex-col gap-3 sm:flex-row"><Link href="/demo" className="inline-flex items-center justify-center gap-2 rounded-xl border border-white/25 px-6 py-3.5 font-semibold transition hover:bg-white/10"><Play size={17} /> View demo</Link><Link href="/onboarding?role=creator" className="inline-flex items-center justify-center gap-2 rounded-xl bg-white px-6 py-3.5 font-semibold text-[#171a20] transition hover:bg-[#dce8ff]">Join as a creator <ArrowRight size={17} /></Link></div></div>
      </section>
    </main>
  );
}

function Benefit({ icon: Icon, title, text }: { icon: typeof UsersRound; title: string; text: string }) {
  return <article className="rounded-2xl border border-[#e7e5e1] bg-white p-7 shadow-[0_12px_28px_rgba(28,34,46,.045)]"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#eef3ff] text-[#315ef5]"><Icon size={20} /></span><h3 className="mt-8 text-xl font-semibold tracking-[-.04em]">{title}</h3><p className="mt-3 text-[15px] leading-6 text-[#6e7580]">{text}</p></article>;
}

function WorkflowStep({ number, title, text }: { number: string; title: string; text: string }) {
  return <li className="flex gap-5 rounded-2xl border border-[#e6e7e9] bg-white p-6 sm:p-7"><span className="text-sm font-bold tracking-[.16em] text-[#315ef5]">{number}</span><span><h3 className="text-xl font-semibold tracking-[-.04em]">{title}</h3><p className="mt-2 text-[15px] leading-6 text-[#6e7580]">{text}</p></span></li>;
}
